### ISSUE TITLE
More detailed installation instructions

### ISSUE THREAD

**Issue by houshuang** [zotero/translation-server-old#1]
I am very interested in getting this to run on my computer, and emit bibtex for a scholarly workflow I have built. It would be amazing if Zotero could operate this server as a public service too. However, currently the installation instructions are very minimal, and I am not sure what to do. Could you please provide more specific installation instructions (I'm on a Mac, although I will probably want to deploy it to a Linux server eventually). Also how to submit URLs to scrape once the server is running.

**Comment by jasonm** [comment]
Ah, just realized, this is addressed by #2 and can be closed.
