### ISSUE TITLE
Use Firefox SDK instead of XULRunner SDK

### ISSUE THREAD

**Issue by simonster** [zotero/translation-server-old#24]
Since Firefox 41, Mozilla no longer builds XULRunner, but they now build a Firefox SDK. translation-server only needs xpcshell, which seems to be included in the Firefox SDK. Getting things working is probably just a matter of playing with some paths.

**Comment by fbennett** [comment]
I've set up a fresh local copy of `translation-server` that runs. It fails on a test page (an SSRN article page), but fetching via the Zotero translation-server instance (using the Google Chrome plugin) does work. Would I be right to guess that it's a version mismatch issue in my newly built source?

If so:
- Would it be better to downgrade Zotero or to upgrade the SDK?
- If upgrading the SDK is the way to go, is a link available for the Firefox SDK? (I wasn't able to locate it by searching and rummaging)

**Comment by dstillman** [comment]
@fbennett: Better to open a new issue with an example URL.

**Comment by zuphilip** [comment]
I think the Firefox SDK v46.0.1 (Build 1) can be found here http://ftp.mozilla.org/pub/firefox/candidates/46.0.1-candidates/build1/firefox-46.0.1.linux-x86_64.sdk.tar.bz2 (Right?). A lot of pages from Mozilla are outdated and I had also a lot of problems to find it.

**Comment by kba** [comment]
From what I've seen on the mailing list [here](https://groups.google.com/forum/#!searchin/mozilla.dev.platform/xulrunner/mozilla.dev.platform/o99wQZBjIJw/4eBoWbjEzjAJ) and [here](https://groups.google.com/forum/#!searchin/mozilla.dev.platform/xulrunner/mozilla.dev.platform/_rFMunG2Bgw/C-4PcHj9IgAJ) XULRunner's future looks rather grim. There is a [Github repo](https://github.com/duanyao/xulrunner-stub) to maintain a community-driven XUL Runner implementation. I only find the (node-based) extension SDK for most searches. The documentation on [XUL Runner](https://developer.mozilla.org/en-US/docs/Archive/Mozilla/XULRunner) and related technologies is marked deprecated without a hint on what's currently recomended to run Firefox/Gecko headless. The docs on [xpcshell](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Language_bindings/XPConnect/xpcshell) only state that it must be built from source.

**Comment by dstillman** [comment]
Yes, XULRunner is discontinued — that's the point of this ticket, to use the Firefox SDK instead. As @simonster says, the SDK includes xpcshell, but we haven't tried hooking it up yet.

The SDK is provided at the root of each release version directory (e.g., http://ftp.mozilla.org/pub/firefox/releases/46.0.1/firefox-46.0.1.linux-x86_64.sdk.tar.bz2).

(Zotero itself will be rebuilt on Electron in the future, at which point translation-server should become much simpler.)

**Comment by kba** [comment]
I made a first draft here that works with the current SDKs: https://github.com/kba/translation-server/commit/8c8ff06a20a4107bb0ec8da00bf0ca959367984b
