### ISSUE TITLE
Docker (contd)

### ISSUE THREAD

**Issue by zuphilip** [zotero/translation-server-old#25]
Okay, my PR #21 is merged now (I copied my last comment here for further discussion). Let us see how to continue:
- @dstillman : would you like to create a docker login for zotero and distribute the official `translation-server` at some adress like https://hub.docker.com/r/zotero/translation-server ? A webhook from the github repo here would make sense to automatically have always the newest docker container. If I understood @kba correctly you could then even trigger that image to rebuild automatically on new commits to the zotero or commits to translators repo. Moreover, might in the future also make sense to provide some docker file for the `data-server`...
- Konstantin: Do you want to make a new PR now here with your improvements? The smaller size looks really good and more automatism sound also fine (also I am not sure that this deletion https://github.com/kba/translation-server/commit/ce46a798be69fee78482179f6680db34a485e0b1#diff-5e7263385927431c0b62df682337b5f8L1 is intended, but I guess it is easier to discuss in a new PR).
- I will try to improve the `README.md` and also mention the docker image which we have now.

**Comment by kba** [comment]
- This should be deferred until #24 is resolved
- Docker images should be built from `git clone zotero/translation-server`, i.e. without any prerequisites, so it can be automatically built on [Docker Hub](http://hub.docker.com).
- There could be web hooks from Github repos for zotero, transslators and translation-server to the translation-server Docker repo, so the docker image is rebuilt whenever any components are updated.

**Comment by dstillman** [comment]
Available as [zotero/translation-server](https://hub.docker.com/r/zotero/translation-server/)

**Comment by kba** [comment]
Any particular reason why you did not create an automated build? As it is, you'll need to push the image whenever the repository is updated (e.g. the zotero submodule bumped).

**Comment by dstillman** [comment]
I don't want to push broken builds. We'll be using the Docker images ourselves in production, so we'll push new builds when there are substantive changes and after appropriate testing. (And we definitely wouldn't want to update on every Zotero changes, because most are irrelevant to translation-server and can easily cause breakage.)

I'm working on [better translator updating](https://github.com/zotero/translation-server/issues/37), though.
