### ISSUE TITLE
Export endpoint fails currently

### ISSUE THREAD

**Issue by zuphilip** [zotero/translation-server-old#28]
I think with the new updated Zotero version, which we use now here in translation-server, the `export` endpoint is not working anymore. The following error message will occur:

```
zotero(3)(+0000002): Zotero.Utilities.itemToExportFormat is not a function at chrome://translation-server/content/translate_item.js:52
```

This function [`itemToExportFormat`](https://github.com/zotero/zotero/blob/master/chrome/content/zotero/xpcom/utilities_internal.js#L768) changed its location to `Zotero.Utilities.Internal` with https://github.com/zotero/zotero/commit/47bf9c38e96e41d066a1c267365a6010be42b038. I tried to replace that and load that file in the same way as `utilities.js` in `build.sh` and `init.js`, but this didn't work out for me :-( Actually, the building process looks ok, but then running the translation-server will just silently quit.

**Comment by zuphilip** [comment]
Ui, I had a typo in my fix. Now, the fix may work...

**Comment by kba** [comment]
Just a quick hint for the silently quitting: Wrap the code you think might break in a `try { .. } catch (e) { dump(e); }` clause.

**Comment by kba** [comment]
I started to debug this in https://github.com/kba/translation-server/tree/debug-issue-28 but gotta go now . if you're interested, try the `test.sh` script and check the `server.log`. `itemToExportFormat` is called but there is an exception `Exception: TypeError: zoteroItem.toJSON is not a function` thrown in `utilities_internal.js`.

**Comment by zuphilip** [comment]
_This partially overlapped with the answer some minutes ago from @kba_

Thank you. I can load now `utilities_internal.js` but the function then relies on another function:

```
string => TypeError: zoteroItem.toJSON is not a function
stack => Zotero.Utilities.Internal.itemToExportFormat</<@chrome://translation-server/content/utilities_internal.js:388
```

I think that this function is inside `item.js` and therefore I tried to load that as well w/o success. Here is my current attempt: https://github.com/zuphilip/translation-server/commit/c1cc9d3b95bac12c27145d98c4634a082e7214c3 

Maybe someone (more experienced) can continue from here? CC @dstillman 

Moreover, I am not sure, that loading more and more JavaScript files is best we can do here...

**Comment by kba** [comment]
The problem is that `itemToExportFormat` expects the parameter to be a `Zotero.Item` object, not a plain JSON object. But we already have the exported format.

Hence:

Replacing

```js
var item = Zotero.Utilities.itemToExportFormat(this._itemsLeft.shift());
```
with
```js
vat item = this._itemsLeft.shift()
```

works for me.

**Comment by zuphilip** [comment]
Yes, I can confirm that this seems to work. Moreover, I added
`item.attachments = [];` when this property is missing and the same for
`notes`. Afterwards most of the export translators are working...

2016-06-05 15:51 GMT+02:00 Konstantin Baierer notifications@github.com:

**Comment by kba** [comment]
`itemToExportFormat` has support for backwards-compatibility transformations in  [addCompatibilityMappings](https://github.com/zotero/zotero/blob/7f339af1042b36362912832e6c6e506e4dec01c8/chrome/content/zotero/xpcom/utilities_internal.js#L769). I don't know how many translators this concerns.
