### ISSUE TITLE
Various document properties are inaccessible

### ISSUE THREAD

**Issue by dstillman** [zotero/translation-server-old#36]
See http://zotero-translator-tests.s3-website-us-east-1.amazonaws.com/testTranslators.html#date=2016-09-01&browser=v&version=4.0.SOURCE for lots of failures.

**Comment by zuphilip** [comment]
I just briefly glanced at the tests, but it seems that tests for `multiples` are failing more often...

**Comment by dstillman** [comment]
Should be obsoleted by v2

**Comment by zuphilip** [comment]
Are the translators already running with v2 now?

**Comment by dstillman** [comment]
Where? Tests [aren't yet implemented](https://github.com/zotero/translation-server/issues/36).

**Comment by zuphilip** [comment]
Ah, I missed that issue. Thank you for the pointer!
