### ISSUE TITLE
Pull new translators on server start

### ISSUE THREAD

**Issue by dstillman** [zotero/translation-server-old#37]
Non-Docker consumers can do this easily out-of-band from whatever process manager calls `run_translation-server.sh`, but Docker consumers will just get translators from the `zotero` branch at the time of the last image build. `run_translation-server.sh` can be made to update translators in `modules/zotero/translators` automatically.

We could do something in-band with git or the translator repo, but a daily restart is probably necessary anyway to combat memory leaks (or it was with XULRunner 39, at least), so that's not a priority.

**Comment by zuphilip** [comment]
Well, personally I mount the translators from outside into the docker container with something like:

```
docker run --rm -p 1969:1969  -v `${PWD}/translators:/opt/zts/modules/zotero/translators` translation-server
```

In my outside normal environment I can fully control which version of the translators repo I would like to use, or I can work on a different fork which is not `master`.

Maybe, you also want to look at what @kba made on top of translation-server etc. with docker compose: https://github.com/kba/zts-in-a-box .
