### ISSUE TITLE
libgtk-3.so.0 Not Found

### ISSUE THREAD

**Issue by stevemk14ebr** [zotero/translation-server-old#39]
I'm receiving this error when attempting to run build/run_translation-server.sh

I'm running this inside a bash shall that is running under the windows subsystem for linux. I followed all of the steps in your build guide, what can i attempt to do to solve this?

`steve@STEVELAPTOP:/mnt/c/Users/Steve/Documents/GitHub/translation-server$ build/run_translation-server.sh
./xpcshell: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory`

**Comment by dstillman** [comment]
On a system without Firefox you'll want to run this inside Docker, which installs [various libraries](https://github.com/zotero/translation-server/blob/3bf240daf7c2857a55fa7bc3bb9f87278f05bd39/Dockerfile#L4) required by current versions of the Firefox SDK on which translation-server is based.

**Comment by dstillman** [comment]
(I've updated the Readme to clarify this.)
