### ISSUE TITLE
API returns 500 for format=biblatex

### ISSUE THREAD

**Issue by adam3smith** [zotero/translation-server-old#50]
`https://api.zotero.org/users/475425/collections/9KH9TNSJ/items?format=bibtex`

works fine

`https://api.zotero.org/users/475425/collections/9KH9TNSJ/items?format=biblatex`
returns an error (both in browser and with curl). `curl -v` returns

```< HTTP/1.1 500 Internal Server Error
< Date: Mon, 11 Sep 2017 03:36:44 GMT
< Server: Apache/2.4.25 (Amazon)
< Zotero-API-Version: 3
< Content-Length: 17
< Content-Type: text/html; charset=UTF-8
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
```

**Comment by dstillman** [comment]
Should be fixed.
