### ISSUE TITLE
Push new version based on Zotero 5.0 to Dockerhub

### ISSUE THREAD

**Issue by zuphilip** [zotero/translation-server-old#55]
Promised [in the phabricator discussion last month](https://phabricator.wikimedia.org/T187194#3968832):

>The current version available on Docker Hub is based on Zotero 4.0, but a version based on Zotero 5.0 has been available on GitHub since June 2017, and that's what we'd recommend using. We'll push that to Docker Hub soon.

This may depend on some other open issues, which have to been resolve before.

**Comment by dstillman** [comment]
Obsoleted by v2
