### ISSUE TITLE
Nested submodules need updating

### ISSUE THREAD

**Issue by tnajdek** [zotero/translation-server-old#58]
When building locally from scratch, calling `/search` endpoint results in:

````
zotero(3)(+0000002): [JavaScript Error: "translator.getCode is not a function" {file: "chrome://translation-server/content/translation/translate.js" line: 1811}] at undefined:1811
````

Running the following command fixes the issue:

    git submodule update --recursive --remote

**Comment by dstillman** [comment]
I assume this is with a manual installation, which unlike Docker installs doesn't have the latest translators. I've [updated](https://github.com/zotero/translation-server/commit/01dc8b1c53485614fa0491255b4989d40191dde8) the manual-install instructions to include a git pull for those.
